#ifndef LLVM_MSTL_PIECEWISE_CONSTURCT_H
#define LLVM_MSTL_PIECEWISE_CONSTURCT_H

#include "__config.h"

LLVM_MSTL_BEGIN_NAMESPACE_STD

// struct LLVM_MSTL_TEMPLATE_VIS

LLVM_MSTL_END_NAMESPACE_STD

#endif//LLVM_MSTL_PIECEWISE_CONSTURCT_H